### PR TITLE
docker: pin to bullseye instead of sid

### PR DESCRIPTION
**Pull request by tmatth**
This avoids the libsoup2/3 conflict described in #13

### CODE REVIEW

**Comment by tmatth** [comment]
N.B. `buster` is the latest stable but the build fails on:
```
 > [4/5] RUN git clone https://github.com/meetecho/simple-whip-client.git && cd simple-whip-client && make:                                                                                    
0.281 Cloning into 'simple-whip-client'...
0.662 Requested 'gstreamer-webrtc-1.0 >= 1.16' but version of GStreamer WebRTC is 1.14.4
0.662 Requested 'gstreamer-sdp-1.0 >= 1.16' but version of GStreamer SDP Library is 1.14.4
0.663 gcc   -D_GNU_SOURCE -fPIC -g -ggdb -c src/whip-client.c -o src/whip-client.o -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wunused 
0.678 src/whip-client.c:19:10: fatal error: gst/gst.h: No such file or directory
0.678  #include <gst/gst.h>
0.678           ^~~~~~~~~~~
0.678 compilation terminated.
0.679 make: *** [Makefile:11: src/whip-client.o] Error 1
------
```

**Comment by tmatth** [comment]
N.B. `bookworm` is the latest stable release but it suffers from the same issue:
```
(whip-client:7): libsoup-ERROR **: 20:01:47.003: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
```

**Comment by lminiero** [comment]
The problem is that in the code we use libsoup2, but we link to gstreamer that builds against libsoup3. As such, the fix is not as simple as changing the docker base, but needs changes to the code too, and even then it's not really fixed, since we may be using libsoup3 but linking against a gstreamer that uses libsoup2. There's no "win", out of choosing one and hoping it will work, or allowing for building against one or the other, and leaving it up to whoever built it to ensure the same version is used in gstreamer. Either that, or get rid of libsoup and use a different HTTP client, but that sounds like way too much effort I'm not really interested in carrying on.

**Comment by tmatth** [comment]
> The problem is that in the code we use libsoup2, but we link to gstreamer that builds against libsoup3. As such, the fix is not as simple as changing the docker base, but needs changes to the code too, and even then it's not really fixed, since we may be using libsoup3 but linking against a gstreamer that uses libsoup2. There's no "win", out of choosing one and hoping it will work, or allowing for building against one or the other, and leaving it up to whoever built it to ensure the same version is used in gstreamer. Either that, or get rid of libsoup and use a different HTTP client, but that sounds like way too much effort I'm not really interested in carrying on.

Yeah I'm aware of the clash, this PR avoids it simply because the `libsoup3` is not present on debian bullseye so gstreamer *can't* be built against it:

image

https://packages.debian.org/search?searchon=sourcenames&keywords=libsoup

**Comment by lminiero** [comment]
Aaah got it, I thought the aim was different!

**Comment by lminiero** [comment]
Then it's good for me to merge, thanks!

**Pull request merged**
